### ISSUE TITLE
Diseñar una Base de Datos

### ISSUE THREAD

**Issue by jpbarahona** [Jupaba/ccientifica#4]
Desarrollar un modelo entidad relación y capaz de soportar un ETL para nuestro sistema, de los datos que nosotros trabajaremos, ya sean txt de entrada y salida, de parametros y resultados respectivos, con los gráficos de solución.

**Comment by jpbarahona** [comment]
Subi al drive el modelo que creo que debemos utilizar para el proyecto, espero que lo vean y comenten...

jpg
https://drive.google.com/file/d/0B4EYb0ZelqrodTI3aGpYNGNwZlE/view?usp=sharing

download mysql.workbench
https://drive.google.com/file/d/0B4EYb0ZelqroRHJET3lJSk9GZTA/view?usp=sharing

Mas que nada, separa los fundamentos matemáticos y se diferencian sus métodos con los algoritmo hechos. También guarda la ruta del txt de entrada, identificando si con esos parametros en la función fx, el algoritmo se cae o no y por ultimo, guarda la ruta del txt de salida con su solución y tabla de resultados.

Para hacer este modelo de base de datos tuve que especificar los objetivos y requerimientos necesarios para el proyecto, que tambien los subi al drive...

https://drive.google.com/file/d/0B4EYb0ZelqroT1p0dzFlNWpLMDA/view?usp=sharing

**Comment by mfdebian** [comment]
pulento :)

**Comment by Gonzalo-C** [comment]
esta bueno!!!
